config/routes.rb
Rails.application.routes.draw do
  get "available" => "calls#available"
  get "scheduled" => "calls#scheduled"
  get "past" => "calls#past"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  resources :calls
  resources :coaches
  resources :students
  resources :users
  resources :sessions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "calls#scheduled"
end

app/models/call.rb
class Call < ApplicationRecord
  belongs_to :coach
  belongs_to :student, optional: true

  validate :overlap
  validates :start, presence: true

  nilify_blanks

  # Currently assumed that meetings are always 2 hours long
  DURATION = 2.hours

  private

  def overlap
    return unless start

    finish = start + DURATION
    two_hours_before_start = start - DURATION
    if !Call.where(coach: coach, start: two_hours_before_start..finish).where.not(id: id).empty?
      errors.add(:start, " overlaps another meeting")
    end
  end
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_action :set_call, only: %i[ show edit update destroy ]
  before_action :set_role
  before_action :redirect_to_login
  before_action :redirect_student, only: %i[ new destroy ]

  # GET /calls or /calls.json
  def index
    @calls = @calls_provider.all(params[:page])
  end

  def past
    @calls = @calls_provider.past(params[:page])
  end

  def scheduled
    @calls = @calls_provider.scheduled(params[:page])
  end

  def available
    @calls = @calls_provider.available(params[:page])
  end

  # GET /calls/1 or /calls/1.json
  def show
  end

  # GET /calls/new
  def new
    @call = Call.new
  end

  # GET /calls/1/edit
  def edit
  end

  # POST /calls or /calls.json
  def create
    @call = Call.new(availability_params)
    @call.coach = current_user

    respond_to do |format|
      if @call.save
        format.html { redirect_to call_url(@call), notice: "Call was successfully created." }
        format.json { render :show, status: :created, location: @call }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calls/1 or /calls/1.json
  def update
    respond_to do |format|
      if @call.update(call_params)
        format.html { redirect_to call_url(@call), notice: "Call was successfully updated." }
        format.json { render :show, status: :ok, location: @call }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calls/1 or /calls/1.json
  def destroy
    @call.destroy!

    respond_to do |format|
      format.html { redirect_to calls_url, notice: "Call was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_call
    @call = Call.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def call_params
    params.require(:call).permit(:coach_id, :student_id, :start, :satisfaction, :notes)
  end

  def availability_params
    params.require(:call).permit(:start)
  end

  def set_role
    @calls_provider = CallsProviderFactory.for(current_user)
    @role ||= current_user && current_user.type == "Coach" ? :coach : :student
  end

  def redirect_to_login
    redirect_to login_path unless current_user
  end

  def redirect_student
    redirect_to root_path unless coach?
  end
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/_availability.html.erb
<%= form_with(model: call) do |form| %>
  <% if call.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
        <% call.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start, style: "display: block" %>
    <%= form.datetime_field :start %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/calls/_availability_form.html.erb
<%= form_with(model: call) do |form| %>
  <% if call.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
        <% call.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start, style: "display: block" %>
    <%= form.datetime_field :start %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/calls/_call.html.erb
<% if coach? %>
  <div id="<%= dom_id call %>">
  <% if call.student %>
    <p>
      <strong>Student:</strong>
      <%= call&.student&.name %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= call&.student&.phone %>
    </p>
  <% end %>

  <p>
    <strong>Start:</strong>
    <%= call&.start %>
  </p>

  <% if call.satisfaction %>
    <p>
      <strong>Satisfaction:</strong>
      <%= call&.satisfaction %>
    </p>
  <% end %>

  <% if call.notes %>
    <p>
      <strong>Notes:</strong>
      <%= call&.notes %>
    </p>
  <% end %>

</div>
<% else %>
  <div id="<%= dom_id call %>">
  <p>
    <strong>Coach:</strong>
    <%= call&.coach&.name %>
  </p>

  <% if call&.student %>
    <p>
      <strong>Phone:</strong>
      <%= call&.coach&.phone %>
    </p>
  <% end %>

  <p>
    <strong>Start:</strong>
    <%= call&.start %>
  </p>

</div>
<% end %>

app/views/calls/_call_list.html.erb
<div id="calls">
  <% @calls.each do |call| %>
    <%= render call %>
    <p>
      <%= link_to "Show this call", call %>
    </p>
  <% end %>
</div>

<%= paginate @calls %>

app/views/calls/_coach_form.html.erb
<%= form_with(model: call) do |form| %>
  <% if call.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
        <% call.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if call.start && call.start < Time.zone.now %>
    <div>
      <%= form.label :satisfaction, style: "display: block" %>
      <%= form.number_field :satisfaction %>
    </div>

    <div>
      <%= form.label :notes, style: "display: block" %>
      <%= form.text_area :notes %>
    </div>
  <% else %>
    <div>
      <%= form.label :start, style: "display: block" %>
      <%= form.datetime_field :start %>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/calls/_form.html.erb
<%= form_with(model: call) do |form| %>
  <% if call.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
        <% call.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :coach_id, style: "display: block" %>
    <%= form.text_field :coach_id %>
  </div>

  <div>
    <%= form.label :student_id, style: "display: block" %>
    <%= form.text_field :student_id %>
  </div>

  <div>
    <%= form.label :start, style: "display: block" %>
    <%= form.datetime_field :start %>
  </div>

  <div>
    <%= form.label :satisfaction, style: "display: block" %>
    <%= form.number_field :satisfaction %>
  </div>

  <div>
    <%= form.label :notes, style: "display: block" %>
    <%= form.text_area :notes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/calls/_student_form.html.erb
<%= render call %>

<%= form_with(model: call) do |form| %>
  <% if call.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(call.errors.count, "error") %> prohibited this call from being saved:</h2>

      <ul>
        <% call.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if call.student %>
    <div>
      <%= form.hidden_field :student_id, value: nil %>
    </div>

    <div>
      <%= form.submit "Cancel Call" %>
    </div>
  <% else %>
    <div>
      <%= form.hidden_field :student_id, value: current_user.id %>
    </div>

    <div>
      <%= form.submit "Book Call" %>
    </div>
  <% end %>
<% end %>

app/views/calls/available.html.erb
<h1>Availability</h1>

<%= render "call_list" %>

<% if coach? %>
<%= link_to "Add Availability", new_call_path %>
<% end %>

app/views/calls/edit.html.erb
<h1>Update call</h1>

<% if coach? %>
<%= render "coach_form", call: @call %>
<% else %>
<%= render "student_form", call: @call %>
<% end %>

<br>

<div>
  <%= link_to "Show this call", @call %> |
  <%= link_to "Back to calls", calls_path %>
</div>

app/views/calls/index.html.erb
<h1>All Calls</h1>

<%= render "call_list" %>

<% if coach? %>
<%= link_to "Add Availability", new_call_path %>
<% end %>

app/views/calls/new.html.erb
<h1>Add Availability</h1>

<%= render "coach_form", call: @call %>

<br>

<div>
  <%= link_to "Back to calls", calls_path %>
</div>

app/views/calls/past.html.erb
<h1>Past Calls</h1>

<%= render "call_list" %>

app/views/calls/scheduled.html.erb
<h1>Scheduled Calls</h1>

<%= render "call_list" %>

app/views/calls/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @call %>

<div>
  <%= link_to "Edit this call", edit_call_path(@call) %> |
  <%= link_to "Back to calls", calls_path %>

  <% if coach? %>
  <%= button_to "Destroy this call", @call, method: :delete %>
  <% end %>
</div>