config/routes.rb
Rails.application.routes.draw do
  get "available" => "calls#available"
  get "scheduled" => "calls#scheduled"
  get "past" => "calls#past"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  resources :calls
  resources :coaches
  resources :students
  resources :users
  resources :sessions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "calls#scheduled"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scaffolded</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if current_user %>
    <%= "Logged in as #{current_user.name}" %> |
    <%= link_to "log out", logout_path %> |
    <%= link_to "availability", available_path %> |
    <%= link_to "scheduled calls", scheduled_path %> |
    <%= link_to "past calls", past_path %> |
    <%= link_to "all calls", calls_path %>
    <% else %>
    <%= link_to "log in", login_path %>
    <% end %>
    <%= yield %>
  </body>
</html>